app-teste/Controllers/MarcaController.cs
using app_teste.Models.DTO.Marca;
using app_teste.Services.Service.Marca;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace app_teste.Controllers
{
    public class MarcaController : Controller
    {
        #region ' Variaveis '
        private readonly MarcaService _service;

        public MarcaController(MarcaService service)
        {
            _service = service;
        }
        #endregion

        #region ' CRUD '
        [HttpGet]
        public IActionResult Index()
        {
            return View(_service.ListarMarca());
        }

        [HttpGet]
        public IActionResult InserirMarca()
        {
            return View();
        }

        [HttpPost]
        public IActionResult InserirMarca([FromServices] MarcaService _service, [FromForm] MarcaDTO marcaDTO)
        {
            _service.InserirMarca(marcaDTO);

            return RedirectToAction("Index");
        }

        [HttpPut]
        public void AlterarStatusMarca([FromServices] MarcaService _service, [FromForm] MarcaDTO marcaDTO)
        {
            _service.AlterarStatusMarca(marcaDTO);
        }
        #endregion

        #region ' Consulta/Grid '
        [HttpGet]
        public IActionResult Grid()
        {
            return PartialView("_Grid", _service.ListarMarca());
        }

        [HttpGet]
        public List<MarcaDTO> ListarMarca()
        {
            return _service.ListarMarca();
        }
        #endregion

    }
}

app-teste/Controllers/ProprietarioController.cs
using app_teste.Models.DTO.Proprietario;
using app_teste.Services.Service.Proprietario;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace app_teste.Controllers
{
    public class ProprietarioController : Controller
    {
        #region ' Variaveis '
        private readonly ProprietarioService _service;

        public ProprietarioController(ProprietarioService service)
        {
            _service = service;
        }
        #endregion

        #region ' CRUD '
        [HttpGet]
        public IActionResult Index()
        {
            return View(_service.ListarProprietario());
        }

        [HttpPost]
        public IActionResult ObterProprietario(int id)
        {
            return View(_service.ObterProprietario(id));
        }

        [HttpGet]
        public IActionResult SalvarProprietario([FromServices] ProprietarioService _service, int? id)
        {
            ProprietarioDTO proprietarioDTO = new ProprietarioDTO();

            if (id.HasValue && id.Value > 0)
                proprietarioDTO = _service.ObterProprietario(id.Value);

            return View(proprietarioDTO);
        }

        [HttpPost]
        public IActionResult SalvarProprietario([FromServices] ProprietarioService _service, [FromForm] ProprietarioDTO proprietarioDTO)
        {
            try
            {
                if (proprietarioDTO.Id > 0)
                    _service.AlterarProprietario(proprietarioDTO);
                else
                    _service.InserirProprietario(proprietarioDTO);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(proprietarioDTO);
            }
        }

        #endregion

        #region ' Consulta/Grid '
        [HttpGet]
        public IActionResult Grid()
        {
            return PartialView("_Grid", _service.ListarProprietario());
        }

        [HttpGet]
        public List<ProprietarioDTO> ListarProprietario()
        {
            return _service.ListarProprietario();
        }
        #endregion

    }
}

app-teste/Controllers/VeiculoController.cs
using app_teste.Models.DTO.Veiculo;
using app_teste.Services.Service.Veiculo;
using Microsoft.AspNetCore.Mvc;

namespace app_teste.Controllers
{
    public class VeiculoController : Controller
    {
        #region ' Variaveis '
        private readonly VeiculoService _service;

        public VeiculoController(VeiculoService service)
        {
            _service = service;
        }
        #endregion

        [HttpGet]
        public IActionResult Index()
        {
            return View(_service.ListarVeiculo());
        }

        [HttpGet]
        public IActionResult Grid()
        {
            return PartialView("_Grid", _service.ListarVeiculo());
        }

        [HttpPost]
        public IActionResult ObterVeiculo(int id)
        {
            return View(_service.ObterVeiculo(id));
        }

        [HttpGet]
        public IActionResult SalvarVeiculo([FromServices] VeiculoService _service, int? id)
        {
            VeiculoDTO veiculoDTO = new VeiculoDTO();

            if (id.HasValue && id.Value > 0)
                veiculoDTO = _service.ObterVeiculo(id.Value);

            ViewBag.ListaProprietario = _service.ListarProprietario();
            ViewBag.ListaMarca = _service.ListarMarca();
            ViewBag.ListaStatus = _service.ListarStatus();

            return View(veiculoDTO);
        }

        [HttpPost]
        public bool SalvarVeiculo([FromServices] VeiculoService _service, [FromForm] VeiculoDTO veiculoDTO)
        {
            bool sucesso = false;

            if (veiculoDTO.Id > 0)
                sucesso = _service.AlterarVeiculo(veiculoDTO);
            else
                sucesso = _service.InserirVeiculo(veiculoDTO);

            return sucesso;

        }
    }
}

app-teste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - app_teste</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">app_teste</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proprietario" asp-action="Index">Proprietarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="Index">Marcas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Veiculo" asp-action="Index">Veiculos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - app_teste @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>